# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # Use match to ensure the correct provisioning profiles are used
    match(type: "appstore")
    #match(type: "appstore", readonly: false, keychain_password: ENV["MATCH_PASSWORD"])

    increment_build_number(xcodeproj: "FastlaneCICDApp.xcodeproj")
    build_app(scheme: "FastlaneCICDApp")
    upload_to_testflight
  end
end
