#name: Fastlane CI/CD
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  build:
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Setup Ruby
#        uses: ruby/setup-ruby@v1
#        with:
#          ruby-version: '3.0'
#
#      - name: Install Bundler
#        run: gem install bundler
#
#      - name: Install Dependencies
#        run: bundle install
#
#      - name: Run Fastlane
#        run: bundle exec fastlane beta



name: Fastlane CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install Bundler
        run: gem install bundler

      - name: Install Dependencies
        run: bundle install

      - name: Set Match Password
        run: echo "::set-env name=MATCH_PASSWORD::tissaProfile@"

      - name: Run Fastlane
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: bundle exec fastlane beta
